name: Build

on:
  workflow_dispatch:
  issues:
    types:
      - opened
      - edited

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: 0.4.0
    steps:
      - run: |
          cat << 'EOF' | awk 'BEGIN{a=0;b=0;}{b=0;if($0~/```/){b=1}if(a==1&&b==0){print($0)}if(b>0){++a}}' > main.wren
          ${{ github.event.issue.body }}
          EOF
      - run: echo "::set-output name=value::$(head -c 1 main.wren)"
        id: source
      - run: |
          curl -L -o wren.zip "https://github.com/wren-lang/wren-cli/releases/download/$VERSION/wren-cli-linux-$VERSION.zip"
          unzip wren.zip
          mv "wren-cli-linux-$VERSION/wren_cli" ./
          chmod u+x wren_cli
          echo "::set-output name=value::$(./wren_cli main.wren | awk '{printf("%s\\n",$0)}')"
        id: result
        if: ${{ steps.source.outputs.value }}
      - uses: actions/github-script@v5
        with:
          script: |
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: "Result: \n\n```\n${{ steps.result.outputs.value }}```\n"
              })
        if: ${{ steps.result.outputs.value }}
