name: Build

on:
  workflow_dispatch:
  # issues:
  #   types:
  #     - opened
  #     - edited

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: 0.4.0
    steps:
      - run: |
          cat << 'EOF' | awk 'BEGIN{a=0;b=0;}{b=0;if($0~/```/){b=1}if(a==1&&b==0){print($0)}if(b>0){++a}}' > main.wren
          ${{ github.event.issue.body }}
          EOF
      - run: |
          curl -L -o wren.zip "https://github.com/wren-lang/wren-cli/releases/download/$VERSION/wren-cli-linux-$VERSION.zip"
          unzip wren.zip
          mv "wren-cli-linux-$VERSION/wren_cli" ./
          chmod u+x wren_cli
          ./wren_cli main.wren > result
